networks:
  default: development

compiler:
  solc:
    version: "0.8.4"
    remappings: 
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0"

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}